#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "ftpgrab"
name = "FTPGrab"
description.en = "Grab your files periodically from a remote FTP or SFTP server"
description.fr = "Récupérez périodiquement vos fichiers à partir d'un serveur FTP ou SFTP distant."

version = "7.10.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
website = "https://example.com"
demo = "https://demo.example.com"
admindoc = "https://crazymax.dev/ftpgrab/"
userdoc = "https://yunohost.org/apps"
code = "https://github.com/crazy-max/ftpgrab"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    #[install.domain]
    #type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/crazy-max/ftpgrab/releases/download/v7.10.0/ftpgrab_7.10.0_linux_amd64.tar.gz"
    sha256 = "a4d80a5aaee8e4f82e7c13d4fa9b2363612b2e0b9e3e07d2770489410720ba25"

    # autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    #[resources.permissions]
    #main.url = "/"
